Homework 2
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

Read the Mr. Trashweheel dataset.

``` r
trashwheel_df = 
  read_xlsx(
    "./data/Trashwheel.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  ) 
```

Read precipitation data for 2018 and 2017\!

``` r
precip_2018 = 
  read_excel(
    "./data/Trashwheel.xlsx",
    sheet = "2018 Precipitation",
    skip = 1,
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2017 = 
  read_excel(
    "./data/Trashwheel.xlsx",
    sheet = "2017 Precipitation",
    skip = 1,
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

Now combine annual precipitation.

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df = 
  bind_rows(precip_2018, precip_2017) 

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # … with 14 more rows

This dataset contains information from the Mr. Trashwheel Trash
Collector in Baltimore, MD. As trash enters the inner harbor, the
trashwheel collects that trash and stores it in a dumpster. The dataset
contains information on year, month, and trash collected, including some
specific kinds of trash. There are a total of 344 rows in our final
dataset. Additional data sheets include monthly precipitation data. The
median number of sports balls found in a dumpster in 2017 was 8. The
total precipitation in 2018 was 70.33 inches.

## Problem 2

Read the NYC Transit dataset.

``` r
transit_df = 
  read_csv(
    "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line:entry, vending, ada) %>% 
  mutate(entry = recode(entry, YES = "TRUE", NO = "FALSE")) %>% 
  mutate(entry = as.logical(entry))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

This dataset contains information on each entry and exit to and from the
NYC Transit subway system. I have narrowed the dataset to only include
the variables line, station\_name, station\_latitude,
station\_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entrance\_type, entry,
vending, ada. The dataset now includes 1868 rows and 19 columns. I have
cleaned the names to snake case and have changed the variable ‘entry’
from a character vector to a logical vector. These data are not yet
tidy, since the route1-route11 column names contain information that
should be listed in rows.

Answer questions about the dataset.

``` r
distinct(transit_df, line, station_name)
```

    ## # A tibble: 465 x 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # … with 455 more rows

``` r
filter(transit_df, ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    84

``` r
filter(transit_df, vending =='NO' & entry == TRUE) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    69

``` r
filter(transit_df, vending == 'NO') %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   183

There are 465 distinct stations. 84 stations are ADA compliant. Out of
183 stations without vending, 69 stations allow entry.

Create a tidy form of the route names and route numbers.

``` r
transit_tidy =
  transit_df %>%
  mutate_at(vars(route1:route11), as.character) %>%
  pivot_longer(
    route1:route11,
    names_to = "route_name",
    names_prefix = "route",
    values_to = "route_number") %>%
  drop_na(route_number)
```

Answering questions about the distinct stations.

``` r
filter(transit_tidy, route_number == "A") %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   273

``` r
filter(transit_tidy, route_number == "A" & ada == TRUE) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   107

273 distinct stations serve the A. Of these, 107 are ADA compliant.

## Problem 3

Cleaning the data in pols-month.csv.

``` r
pols_df = 
  read_csv("./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(year = as.integer(year)) %>% 
  mutate(month = as.integer(month)) %>% 
  mutate(day = as.integer(day)) 
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name) %>% 
  mutate(month = as.integer(month))
  
pols_df = 
  left_join(pols_df, month_df, by = "month")

pols_df = relocate(pols_df, prez_dem, .after = prez_gop)
  
pols_tidy =
  pivot_longer(
    pols_df,
    prez_gop:prez_dem,
    names_to = "president",
    values_to = "president_value") %>% 
  mutate(president = recode(president, prez_gop = "gop", prez_dem = "dem"))

select(pols_df, -day, -prez_dem, -prez_gop)
```

    ## # A tibble: 822 x 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem month_name
    ##    <int> <int>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     
    ##  1  1947     1      23      51     253      23      45     198 January   
    ##  2  1947     2      23      51     253      23      45     198 February  
    ##  3  1947     3      23      51     253      23      45     198 March     
    ##  4  1947     4      23      51     253      23      45     198 April     
    ##  5  1947     5      23      51     253      23      45     198 May       
    ##  6  1947     6      23      51     253      23      45     198 June      
    ##  7  1947     7      23      51     253      23      45     198 July      
    ##  8  1947     8      23      51     253      23      45     198 August    
    ##  9  1947     9      23      51     253      23      45     198 September 
    ## 10  1947    10      23      51     253      23      45     198 October   
    ## # … with 812 more rows

Cleaning data in snp.csv.

``` r
snp_df = 
  read.csv("./data/snp.csv") %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.integer(year)) %>% 
  mutate(month = as.integer(month)) %>% 
  mutate(day = as.integer(day)) 

snp_df = 
  left_join(snp_df, month_df, by = "month")

snp_df = relocate(snp_df, year, .before = month)
```

Tidy the unemployment data.

``` r
unemployment_df = 
  read.csv("./data/unemployment.csv") 

unemploy_tidy = 
  pivot_longer(
    unemployment_df,
    Jan:Dec,
    names_to = "month_name",
    values_to = "percent") %>% 
  mutate(month_name = month.name[as.factor(month_name)]) %>% 
  mutate(month_name = recode(month_name, January = "1", February = "2", March = "3", April = "4", May = "5", June = "6", July = "7", August = "8", September = "9", October = "10", November = "11", December = "12")) %>% 
  mutate(month_name = as.integer(month_name)) %>%
  rename("month" = "month_name") %>% 
  rename("year" = "Year")
```

Join datasets.

``` r
Combine_df = 
  left_join(pols_tidy, snp_df, by = "month", "year")

final_df = 
  left_join(Combine_df, unemploy_tidy, by = "month", "year") 
```

This final dataset was created by merging data from pols-month.csv,
which contains data on the number of national politicians by party over
time, snp.csv, which contains data on the Standard & Poor’s stock market
index, and unemployment.csv, which contains data on percent unemployment
by month over time. The final dataset has 7332032 rows and 18 columns.
The years included are between 1947, 2015. Variables in the set are:
year.x, month, day.x, gov\_gop, sen\_gop, rep\_gop, gov\_dem, sen\_dem,
rep\_dem, month\_name.x, president, president\_value, year.y, day.y,
close, month\_name.y, year, percent.
